var auto = google.maps.places.Autocomplete('#id');

data = auto.getPlace();

data = {
    "address_components":[
        {
            "long_name":"长沙",
            "short_name":"长沙",
            "types":[
                "locality",
                "political"
            ]
        },
        {
            "long_name":"湖南省",
            "short_name":"湖南省",
            "types":[
                "administrative_area_level_1",
                "political"
            ]
        },
        {
            "long_name":"中国",
            "short_name":"CN",
            "types":[
                "country",
                "political"
            ]
        }
    ],
    "formatted_address":"中国湖南省长沙市",
    "geometry":{
        "location":{
            "Oa":28.228209,
            "Pa":112.93881399999998
        },
        "viewport":{
            "Z":{
                "b":27.9153089,
                "d":28.4369499
            },
            "aa":{
                "b":112.70599370000002,
                "d":113.34320070000001
            }
        }
    },
    "icon":"http://maps.gstatic.com/mapfiles/place_api/icons/geocode-71.png",
    "id":"a61a9d1790be49105b4a91573d0f06e1688545ce",
    "name":"长沙",
    "reference":"CmReAAAAuYf7sRp6U9Aos8nNm29hM-rfuyBeXCIsrXvxRyPMcWwB17uRlb6GoVrSiNN3YRIgbilEPekocOGEA9bZA9A1zk0lf40iXbStvcHVxCEKEWZ37H_YcPLVvqbvlZxSjnEaEhBsp6f8Gd13q_xUucG-l0-HGhQDLFZJNN8YP1qzXEP5_surIleF-g",
    "types":[
        "locality",
        "political"
    ],
    "url":"http://maps.google.com/maps/place?ftid=0x342735f39e1c64c5:0xb1e5bb9ca1f1a680",
    "vicinity":"长沙",
    "html_attributions":[
    ]

}



var marker = new google.maps.Marker({map: 1, draggable: 1, title: 1});
data = marker.getPositon();
data = {"Oa":28.191903835196225,"Pa":112.97177298437498}
data = new google.maps.LatLng(28.188, 113.033);



var geocode = new google.maps.Geocoder();
geocode.geocode(
    {
        location: new google.maps.LatLng(28.188, 113.033)
    }, function(results, status) {
    });
status = "ok"
status = google.maps.GeocoderStatus.OK
result = [
    {
        "address_components":[
            {
                "long_name":"384号-402号",
                "short_name":"384号-402号",
                "types":[
                    "street_number"
                ]
            },
            {
                "long_name":"解放西路",
                "short_name":"解放西路",
                "types":[
                    "route"
                ]
            },
            {
                "long_name":"天心区",
                "short_name":"天心区",
                "types":[
                    "sublocality",
                    "political"
                ]
            },
            {
                "long_name":"长沙",
                "short_name":"长沙",
                "types":[
                    "locality",
                    "political"
                ]
            },
            {
                "long_name":"湖南省",
                "short_name":"湖南省",
                "types":[
                    "administrative_area_level_1",
                    "political"
                ]
            },
            {
                "long_name":"中国",
                "short_name":"CN",
                "types":[
                    "country",
                    "political"
                ]
            }
        ],
        "formatted_address":"中国湖南省长沙市天心区解放西路384号-402号",
        "geometry":{
            "bounds":{
                "Z":{
                    "b":28.191748,
                    "d":28.1918474
                },
                "aa":{
                    "b":112.97169200000008,
                    "d":112.97274110000001
                }
            },
            "location":{
                "Oa":28.1918604,
                "Pa":112.97176769999999
            },
            "location_type":"RANGE_INTERPOLATED",
            "viewport":{
                "Z":{
                    "b":28.1904487197085,
                    "d":28.19314668029151
                },
                "aa":{
                    "b":112.9708675697085,
                    "d":112.97356553029147
                }
            }
        },
        "types":[
            "street_address"
        ]
    },
    {
        "address_components":[
            {
                "long_name":"天心区",
                "short_name":"天心区",
                "types":[
                    "sublocality",
                    "political"
                ]
            },
            {
                "long_name":"长沙",
                "short_name":"长沙",
                "types":[
                    "locality",
                    "political"
                ]
            },
            {
                "long_name":"湖南省",
                "short_name":"湖南省",
                "types":[
                    "administrative_area_level_1",
                    "political"
                ]
            },
            {
                "long_name":"中国",
                "short_name":"CN",
                "types":[
                    "country",
                    "political"
                ]
            }
        ],
        "formatted_address":"中国湖南省长沙市天心区",
        "geometry":{
            "bounds":{
                "Z":{
                    "b":28.0354529,
                    "d":28.1956242
                },
                "aa":{
                    "b":112.92795419999993,
                    "d":113.00754189999998
                }
            },
            "location":{
                "Oa":28.112708,
                "Pa":112.98991699999999
            },
            "location_type":"APPROXIMATE",
            "viewport":{
                "Z":{
                    "b":28.0354529,
                    "d":28.1956242
                },
                "aa":{
                    "b":112.92795419999993,
                    "d":113.00754189999998
                }
            }
        },
        "types":[
            "sublocality",
            "political"
        ]
    },
    {
        "address_components":[
            {
                "long_name":"长沙",
                "short_name":"长沙",
                "types":[
                    "locality",
                    "political"
                ]
            },
            {
                "long_name":"湖南省",
                "short_name":"湖南省",
                "types":[
                    "administrative_area_level_1",
                    "political"
                ]
            },
            {
                "long_name":"中国",
                "short_name":"CN",
                "types":[
                    "country",
                    "political"
                ]
            }
        ],
        "formatted_address":"中国湖南省长沙市",
        "geometry":{
            "bounds":{
                "Z":{
                    "b":27.9153089,
                    "d":28.4369499
                },
                "aa":{
                    "b":112.70599370000002,
                    "d":113.34320070000001
                }
            },
            "location":{
                "Oa":28.228209,
                "Pa":112.93881399999998
            },
            "location_type":"APPROXIMATE",
            "viewport":{
                "Z":{
                    "b":27.9153089,
                    "d":28.4369499
                },
                "aa":{
                    "b":112.70599370000002,
                    "d":113.34320070000001
                }
            }
        },
        "types":[
            "locality",
            "political"
        ]
    },
    {
        "address_components":[
            {
                "long_name":"湖南省",
                "short_name":"湖南省",
                "types":[
                    "administrative_area_level_1",
                    "political"
                ]
            },
            {
                "long_name":"中国",
                "short_name":"CN",
                "types":[
                    "country",
                    "political"
                ]
            }
        ],
        "formatted_address":"中国湖南省",
        "geometry":{
            "bounds":{
                "Z":{
                    "b":24.6363234,
                    "d":30.126363
                },
                "aa":{
                    "b":108.79084130000001,
                    "d":114.26126469999997
                }
            },
            "location":{
                "Oa":28.112444,
                "Pa":112.98380999999995
            },
            "location_type":"APPROXIMATE",
            "viewport":{
                "Z":{
                    "b":24.6363234,
                    "d":30.126363
                },
                "aa":{
                    "b":108.79084130000001,
                    "d":114.26126469999997
                }
            }
        },
        "types":[
            "administrative_area_level_1",
            "political"
        ]
    },
    {
        "address_components":[
            {
                "long_name":"中国",
                "short_name":"CN",
                "types":[
                    "country",
                    "political"
                ]
            }
        ],
        "formatted_address":"中国",
        "geometry":{
            "bounds":{
                "Z":{
                    "b":17.9996,
                    "d":53.56097399999999
                },
                "aa":{
                    "b":73.49941369999999,
                    "d":134.77280999999994
                }
            },
            "location":{
                "Oa":35.86166,
                "Pa":104.19539699999996
            },
            "location_type":"APPROXIMATE",
            "viewport":{
                "Z":{
                    "b":17.9996,
                    "d":53.56097399999999
                },
                "aa":{
                    "b":73.49941369999999,
                    "d":134.77280999999994
                }
            }
        },
        "types":[
            "country",
            "political"
        ]
    }

]
